fm_elfinder:
    assets_path: /assets # chemin des fichiers JS instances: 
    instances:
        default:
            locale: fr # Langue 
            editor: ckeditor # Editeur utilisé
            fullscreen: true # Taille d'affichage
            theme: smoothness # Thème à utiliser
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem # Pilote des fichiers
                        path: uploads/images # Chemin d'upload
                        show_hidden: false # Masque les fichiers cachés
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg', file/pdf] # Fichiers autorisés
                        upload_deny: ['all'] # Fichiers interdits upload_max_size: 4M # Taille maximum     


